#!/bin/sh
# setwallpaper-dmenu by jornmann, original by speedie

die() {
	printf "%s\n" "$1"
	exit 2
}

which feh > /dev/null || die "feh is not installed. Please install it."

wallpaperdirectory="$HOME/.wallpapers"
mkdir "$wallpaperdirectory" 2> /dev/null

wallpaper="$(cd ${wallpaperdirectory} && find | tail -n +2 | cut -c 3- | dmenu -p wallpaper)" || exit

scale=$(printf 'fill\ntile\ncenter\nscale\nmax' | dmenu -p scale) || exit

case "$scale" in
	"fill") scalecmd="--bg-fill" ;;
	"tile") scalecmd="--bg-tile" ;;
	"center") scalecmd="--bg-center" ;;
	"scale") scalecmd="--bg-scale" ;;
	"max") scalecmd="--bg-max" ;;
esac

feh "$scalecmd" "$wallpaperdirectory"/"$wallpaper"
